### PR TITLE
PTX-23350 Vendor changes for libopenstorage/operator

### PR DESCRIPTION
**Pull request by nilanto07-px**
vendoring changes for libopenstorage/operator

### CODE REVIEW

**Review by kphalgun-px — APPROVED** [review]
LGTM

**Review by kphalgun-px — APPROVED** [review]
LGTM

**Review by nikolaypopov — CHANGES_REQUESTED** [review]
Need to vendor latest master commit https://github.com/libopenstorage/operator/commit/c6f4eedd910686107e25257b15689ce70a0095c9

**Review by nikolaypopov — APPROVED** [review]
LGTM

**Pull request merged**
