### PR TITLE
PWX-27967: Increase inspect volume retry sleep time & timeout.

### PR DESCRIPTION
**Pull request by ashinde-px**
**What this PR does / why we need it**:
PWX-27967: [Torpedo][FADA][]Failed to validate device path
- Increased inspect volume retry sleep time by 1 second.
- Increased inspect volume timeout by 1 min

**Which issue(s) this PR fixes** (optional)
Closes #PWX-27967

**Special notes for your reviewer**:

### CODE REVIEW

**Review by Pure-AdamuKaapan — COMMENTED** [review]
Can we try running a nightly job with this fix for a while before we merge it (or if you have, can you link it)? Raising timeouts without showing it helps always worries me

**Comment by nikolaypopov** [comment]
I agree, build a private torpedo image out of this code change and let's see if that fixes the issue.

**Comment by ashinde-px** [comment]
- We ran CI job for FAFB twice for u20 with PXSDK & PXCTL, It worked fine
https://jenkins.pwx.dev.purestorage.com/job/Pure-FAFB/job/CI/job/PWX-27967-u20/2/ 

- We also tried to run the Pure-FAFB Job with our changes and it went well.
https://jenkins.pwx.dev.purestorage.com/job/Pure-FAFB/job/Tests/job/amol-master-torpedo-mount/54/

- Only the Job related to FACD is failing but that's not because of our changes, ES app itself has problem to Run with FACD tests.
https://jenkins.pwx.dev.purestorage.com/job/Pure-FAFB/job/CI/job/PWX-27967-FACD-u20-k540/

**Comment by smaanika-px** [comment]
@nikolaypopov  @Pure-AdamuKaapan - Can you please provide your thoughts?

**Review by Pure-AdamuKaapan — APPROVED** [review]
Hmmm okay, interesting metrics that it passed with a higher timeout. Probably more motivation for us to look into speeding up FlashArray attach times.

LGTM, thanks for testing it out!

**Review by vinayakshnd — APPROVED** [review]
LGTM

**Pull request merged**
