### PR TITLE
DS-9063: Templates(App, Resource and Storage) Creation with expected values

### PR DESCRIPTION
**Pull request by jkagliwal-px**
Fixed the issues in templates values.

Solves ticket - https://purestorage.atlassian.net/browse/DS-9063

```
2024-04-12 21:35:55 +0530:[DEBUG] [{DeployDataServicesOnDemandAndScaleUp}] [pdsLibs.ValidateDataServiceDeployment.func1:#149] - Health status -  AVAILABLE
2024-04-12 21:35:55 +0530:[INFO] [{DeployDataServicesOnDemandAndScaleUp}] [pdsLibs.ValidateDataServiceDeployment.func1:#153] - Deployment details: Health status -  AVAILABLE, Replicas - 2, Ready replicas - 2
2024-04-12 21:35:55 +0530:[DEBUG] [{DeployDataServicesOnDemandAndScaleUp}] [pds2.init.func3.2.3:#73] - Updated Deployment Id: [dcu:e50716e1-6535-4eff-ae62-6ecdef5c35ae]
2024-04-12 21:35:55 +0530:[INFO] [{DeployDataServicesOnDemandAndScaleUp}] Cleaning Up dataservice...
•SSSSSSSSSSSSSSSSSSSSSSSS2024-04-12 21:35:56 +0530:[INFO] Test Finished


Ran 1 of 34 Specs in 285.134 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 33 Skipped
```

BYOC Branch Run - https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/376/console

Build Torpedo - https://jenkins.pwx.dev.purestorage.com/job/Users/job/Madan/job/platfrom-build-torpedo/468/

### CODE REVIEW

**Comment by Madanagopal19** [comment]
kindly run this pipeline https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/ with your branch build

**Comment by jkagliwal-px** [comment]
> Fixed the issues in templates values.
> 
> Solves ticket - https://purestorage.atlassian.net/browse/DS-9063
> 
> ```
> 2024-04-12 21:35:55 +0530:[DEBUG] [{DeployDataServicesOnDemandAndScaleUp}] [pdsLibs.ValidateDataServiceDeployment.func1:#149] - Health status -  AVAILABLE
> 2024-04-12 21:35:55 +0530:[INFO] [{DeployDataServicesOnDemandAndScaleUp}] [pdsLibs.ValidateDataServiceDeployment.func1:#153] - Deployment details: Health status -  AVAILABLE, Replicas - 2, Ready replicas - 2
> 2024-04-12 21:35:55 +0530:[DEBUG] [{DeployDataServicesOnDemandAndScaleUp}] [pds2.init.func3.2.3:#73] - Updated Deployment Id: [dcu:e50716e1-6535-4eff-ae62-6ecdef5c35ae]
> 2024-04-12 21:35:55 +0530:[INFO] [{DeployDataServicesOnDemandAndScaleUp}] Cleaning Up dataservice...
> •SSSSSSSSSSSSSSSSSSSSSSSS2024-04-12 21:35:56 +0530:[INFO] Test Finished
> 
> 
> Ran 1 of 34 Specs in 285.134 seconds
> SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 33 Skipped
> ```
> 
> PS: For full logs please visit the JIRA Ticket.
> 
> Build Torpedo - https://jenkins.pwx.dev.purestorage.com/job/Users/job/Madan/job/platfrom-build-torpedo/468/

**Comment by jkagliwal-px** [comment]
> kindly run this pipeline https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/ with your branch build

Run PASSED - https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/376/console

**Review by Madanagopal19 — APPROVED** [review]
LGTM

**Pull request merged**
