### PR TITLE
Modified rancher testcases to get cluster name

### PR DESCRIPTION
**Pull request by snigdha-px**
**What this PR does / why we need it**:
1)Modified the rke testcases to get cluster name got project creation
2)Modified rke token and URL variable according to latest jenkins changes
**Which issue(s) this PR fixes** (optional)
Closes #https://purestorage.atlassian.net/browse/PB-7330

**Special notes for your reviewer**:
Pass log: https://aetos.pwx.purestorage.com/resultSet/testSetID/686405

### CODE REVIEW

**Review by kshithijiyer-px — APPROVED** [review]
LGTM

**Review by sn-px — APPROVED** [review]
lgtm

**Review by vpinisetti-px — APPROVED** [review]
LGTM

**Review by mkoppal-px — APPROVED** [review]
LGTM

**Review by vpinisetti-px — DISMISSED** [review]
@snigdha-px I'm merging my testcase PSALowerPrivilegeToHigherPrivilegeWithProjectMapping also. Please change the source & destination cluster names.

**Comment by snigdha-px** [comment]
> @snigdha-px I'm merging my testcase PSALowerPrivilegeToHigherPrivilegeWithProjectMapping also. Please change the source & destination cluster names.

sure

**Pull request merged**
