### PR TITLE
[PB-6037]Add receiver and recipient object Support

### PR DESCRIPTION
**Pull request by aks-px**
**What this PR does / why we need it**:
Added support for receiver and recipient objects which is to be used for px-backup automation

**Which issue(s) this PR fixes** (optional)
Closes #PB-6037

**Special notes for your reviewer**:
To avoid exposing credentials,ran it locally.Here's the aetos link :
https://aetos.pwx.purestorage.com/resultSet/testSetID/574786

### CODE REVIEW

**Review by kphalgun-px — APPROVED** [review]
LGTM

**Review by mkoppal-px — APPROVED** [review]
LGTM

**Review by mkoppal-px — CHANGES_REQUESTED** [review]
Why is the test failing?

**Comment by aks-px** [comment]
There is ticket for the failure of this test
https://portworx.atlassian.net/browse/PB-6092

**Review by mkoppal-px — APPROVED** [review]
LGTM

**Pull request merged**
