### PR TITLE
PWX-35590: Added functional test for checking IOpriority of FACD storage pools

### PR DESCRIPTION
**Pull request by ragsingh-px**
**What this PR does / why we need it**:
As per the ticket PWX-35590, we are setting the IO PRiority for FACD pools to HIGH, this test case verifies this.
**Which issue(s) this PR fixes** (optional)
Closes # PWX-35590

**Special notes for your reviewer**:
Testing link:- https://jenkins.pwx.dev.purestorage.com/job/Users/job/Raghvendra/job/ragsingh-facd-job/8

### CODE REVIEW

**Review by pnookala-px — APPROVED** [review]
LGTM

**Comment by nrevanna** [comment]
Will this test run as part of some jenkins job regularly? If so which one?

**Comment by ragsingh-px** [comment]
> Will this test run as part of some jenkins job regularly? If so which one?

We can add this test to run as a part of FACD related jenkins job

**Review by dbhatnagar-px — APPROVED** [review]
Lgtm

**Pull request merged**
