### PR TITLE
Temporary removeal of pvc cleanup validation

### PR DESCRIPTION
**Pull request by snigdha-px**
**What this PR does / why we need it**:
 ValidatePVCCleanup is failing in upgrade pipeline as new pvcs have been introduced in 2.7.0 and validationn is failing
 
**Which issue(s) this PR fixes** (optional)
Closes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by ak-px — APPROVED** [review]
Add a TODO note.
LGTM

**Review by kshithijiyer-px — APPROVED** [review]
lgtm

**Review by mkoppal-px — APPROVED** [review]
LGTM

**Review by vpinisetti-px — APPROVED** [review]
LGTM

**Pull request merged**
