### PR TITLE
Add security annotations to vol snap restore, if required

### PR DESCRIPTION
**Pull request by Rohit-PX**
Why do we need this PR?
For auth runs, vol snap restores are currently failing because security annotations are not being added.

Signed-off-by: Rohit-PX <rohit@portworx.com>

### CODE REVIEW

**Comment by Rohit-PX** [comment]
Tested here: https://jenkins.portworx.co/job/Torpedo/job/tp-dev-test/541/console

**Comment by thiguetta** [comment]
@Rohit-PX run a jenkins job https://jenkins.portworx.co/job/Torpedo/job/tp-dev-test/ using your image, make sure it succeeded at least with these tests SetupTeardown,AppTasksDown,AppScaleUpAndDown,VolumeDriverDown,VolumeDriverAppDown,VolumeDriverDownAttachedNode,VolumeUpdate,RebootOneNode  and apps elasticsearch,mysql,postgres,sysbench,nginx-sharedv4,wordpress-sharedv4

**Comment by thiguetta** [comment]
run a jenkins job https://jenkins.portworx.co/job/Torpedo/job/tp-dev-test/ using your image, make sure it succeeded at least with these tests SetupTeardown,AppTasksDown,AppScaleUpAndDown,VolumeDriverDown,VolumeDriverAppDown,VolumeDriverDownAttachedNode,VolumeUpdate,RebootOneNode and apps elasticsearch,mysql,postgres,sysbench,nginx-sharedv4,wordpress-sharedv4

 I see your test didn't run with any sharedv4

**Comment by Rohit-PX** [comment]
> @Rohit-PX could you please run a jenkins job https://jenkins.portworx.co/job/Torpedo/job/tp-dev-test/ using your image, make sure it succeeded at least with these tests SetupTeardown,AppTasksDown,AppScaleUpAndDown,VolumeDriverDown,VolumeDriverAppDown,VolumeDriverDownAttachedNode,VolumeUpdate,RebootOneNode and apps elasticsearch,mysql,postgres,sysbench,nginx-sharedv4,wordpress-sharedv4
> 
> I see your test didn't run with any sharedv4

Ran here:  https://jenkins.portworx.co/job/Torpedo/job/tp-dev-test/681/parameters/

**Pull request merged**
