### PR TITLE
Update to k8s 1.20 client

### PR DESCRIPTION
**Pull request by ggriffiths**
Signed-off-by: Grant Griffiths <ggriffiths@purestorage.com>

### CODE REVIEW

**Comment by adityadani** [comment]
@harsh-px @ggriffiths Can we prioritize to merge this change so that downstream dependencies of torpedo don't have to develop on top of this 1.20 branch?

**Comment by ggriffiths** [comment]
Yes, I waited to merge this as the torpedo image I built with this code was failing. Let me rebase and try again @adityadani

**Comment by ggriffiths** [comment]
Running this with tp-dev-test build 885 now.

**Comment by ggriffiths** [comment]
Torpedo tests are failing with this branch. @nikolaypopov and @thiguetta are looking into it

**Comment by ggriffiths** [comment]
Updated with latest sched-ops, re-running tp-dev-test with this branch.

**Review by Rohit-PX — APPROVED** [review]
Looks good to me.

**Pull request merged**
