### PR TITLE
Use correct volume name for snapshot

### PR DESCRIPTION
**Pull request by disrani-px**

### CODE REVIEW

**Comment by harsh-px** [comment]
@disrani-px I don't think this is needed after #174 . Can be closed.

**Comment by disrani-px** [comment]
Please update vendor in stork and verify that the test passes there. The test looks for volume name as the key and this sets the volume I'd, so there might be an issue

**Comment by harsh-px** [comment]
> Please update vendor in stork and verify that the test passes there. The test looks for volume name as the key and this sets the volume I'd, so there might be an issue


Sure which test do we need to check? stork-master?

**Comment by disrani-px** [comment]
Any of the jobs. They are all using the master build of stork with different versions of PX

**Comment by harsh-px** [comment]
All tests on all branches are passing with torpedo on master. Closing this one.

**Pull request closed without merging**
