### PR TITLE
Modified app deletion method for MultipleProjectsAndNamespacesBackupA…

### PR DESCRIPTION
**Pull request by snigdha-px**
…ndRestore testcase

**What this PR does / why we need it**:
Testcase MultipleProjectsAndNamespacesBackupAndRestore is failing with namespace in Terminating state even after finaliser is set to nil. using method DeleteAppNamespace
Now using DestroyApps method instead
**Which issue(s) this PR fixes** (optional)
Closes #https://portworx.atlassian.net/browse/PB-4854

**Special notes for your reviewer**:

https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/3319/consoleFull
https://aetos.pwx.purestorage.com/resultSet/testSetID/431706
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/basic-system-test/job/px/job/NFS/job/PX-Cloud-RKE-NFS/194/

### CODE REVIEW

**Review by kphalgun-px — APPROVED** [review]
LGTM

**Comment by mkoppal-px** [comment]
Can you run this once with NFS as well?

**Comment by snigdha-px** [comment]
> Can you run this once with NFS as well?

@mkoppal-px Had started a full NFS run with my branch yesterday since it fails when we give full run on NFS:
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/basic-system-test/job/px/job/NFS/job/PX-Cloud-RKE-NFS/194/

**Review by mkoppal-px — APPROVED** [review]
LGTM

**Review by kshithijiyer-px — APPROVED** [review]
LGTM

**Pull request merged**
