### PR TITLE
Added testcase: LicensingCountBeforeAndAfterBackupPodRestart

### PR DESCRIPTION
**Pull request by snigdha-px**
**What this PR does / why we need it**:
Added a testcase: LicensingCountBeforeAndAfterBackupPodRestart
**Which issue(s) this PR fixes** (optional)
Closes #https://portworx.atlassian.net/browse/PA-912

**Special notes for your reviewer**:

Aetos: https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/1221/consoleFull

*Will remove the method RemoveLabelFromNodesIfPresent once  https://github.com/portworx/torpedo/pull/1348 is merged

### CODE REVIEW

**Review by kphalgun-px — APPROVED** [review]
LGTM

**Review by mkoppal-px — CHANGES_REQUESTED** [review]
Where ever you are printing this line:
```
fmt.Sprintf("Removing label portworx.io/nobackup=true from worker node %s", workerNode))
```
Do not print the `workerNode`, just print `workerNode.name`

Do the same change in all Node license related tests

**Comment by snigdha-px** [comment]
> Where ever you are printing this line:
> 
> ```
> fmt.Sprintf("Removing label portworx.io/nobackup=true from worker node %s", workerNode))
> ```
> 
> Do not print the `workerNode`, just print `workerNode.name`
> 
> Do the same change in all Node license related tests

done

**Review by mkoppal-px — APPROVED** [review]
LGTM

**Pull request merged**
