### PR TITLE
Replacing ValidateBackupCluster function

### PR DESCRIPTION
**Pull request by mkoppal-px**
**What this PR does / why we need it**:
The function `ValidateBackupCluster` was written during the early days of backup automation when we dint not have a separate `backup_helper.go`. During the creation of upgrade test case we wrote a function `ValidateAllPodsInPxBackupNamespace` which does the exact same thing, so we are finally retiring `ValidateBackupCluster`

**Which issue(s) this PR fixes** (optional)
Closes #PA-777

**Special notes for your reviewer**:
[Jenkins Run](https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/1413/)

### CODE REVIEW

**Review by tthurlapati-px — APPROVED** [review]
LGTM

**Comment by kphalgun-px** [comment]
ValidateBackupCluster has a more comprehensive validation approach. Can we retire ValidateAllPodsInPxBackupNamespace instead?

**Review by lsrinivas-pure — APPROVED** [review]
lgtm

**Comment by mkoppal-px** [comment]
> ValidateBackupCluster has a more comprehensive validation approach. Can we retire ValidateAllPodsInPxBackupNamespace instead?

What do you think it is doing extra in order to make sure that Px-Backup is healthy?

**Comment by kphalgun-px** [comment]
> > ValidateBackupCluster has a more comprehensive validation approach. Can we retire ValidateAllPodsInPxBackupNamespace instead?
> 
> What do you think it is doing extra in order to make sure that Px-Backup is healthy?

I am not entirely sure, but the excluded pods might have a different lifecycle compared to other pods in the backup cluster, or the default timeout might be exceeded when validating those pods.

**Comment by mkoppal-px** [comment]
> > > ValidateBackupCluster has a more comprehensive validation approach. Can we retire ValidateAllPodsInPxBackupNamespace instead?
> > 
> > 
> > What do you think it is doing extra in order to make sure that Px-Backup is healthy?
> 
> I am not entirely sure, but the excluded pods might have a different lifecycle compared to other pods in the backup cluster, or the default timeout might be exceeded when validating those pods.

The excluded pods are not indicative of whether the Px-Backup app is healthy or not. We can discuss more on this offline.

**Pull request merged**
