### PR TITLE
PTX-24254:Adding logic to validate pools for limit before expansion

### PR DESCRIPTION
**Pull request by lsrinivas-pure**
**What this PR does / why we need it**:
Adding logic to validate pools for limit before expansion
**Which issue(s) this PR fixes** (optional)
Closes #PTX-24254

**Special notes for your reviewer**:
Result: https://aetos.pwx.purestorage.com/resultSet/testSetID/662781

### CODE REVIEW

**Review by mkoppal-px — APPROVED** [review]
LGTM

**Review by mkoppal-px — CHANGES_REQUESTED** [review]
Please check why the CBT is failing

**Comment by lsrinivas-pure** [comment]
> Please check why the CBT is failing

@mkoppal-px torpedo-cbt passed. can u please approve

**Review by mkoppal-px — APPROVED** [review]
LGTM

**Pull request merged**
