### PR TITLE
Handle Jenkins SIGTERM

### PR DESCRIPTION
**Pull request by kphalgun-px**
**What this PR does / why we need it**:
This PR makes changes to Torpedo script to use SIGKILL upon SIGTERM from Jenkins, ensuring an immediate termination of Ginkgo tests and preventing the execution of the AfterSuite.

**Which issue(s) this PR fixes** (optional)
Closes #PTX-21356

**Special notes for your reviewer**:
Please review the Jenkins build for the test case "SetupTearDown" Without SIGTERM using the link below

https://jenkins.pwx.dev.purestorage.com/job/Users/job/Leela/job/tp-byoc/617/

Aetos Dashboard: https://aetos.pwx.purestorage.com/resultSet/testSetID/455758

Please review the Jenkins build for the test case "SetupTearDown" With SIGTERM using the link below

https://jenkins.pwx.dev.purestorage.com/job/Users/job/Leela/job/tp-byoc/616/

Aetos Dashboard: NA

```
kubectl get pod torpedo
NAME      READY   STATUS   RESTARTS   AGE
torpedo   0/1     Error    0          55s
```

### CODE REVIEW

**Review by mkoppal-px — APPROVED** [review]
LGTM. Ran this branch with all backup tests - [Jenkins run](https://jenkins.pwx.dev.purestorage.com/blue/organizations/jenkins/portworx-backup%2Fsystem-tests%2Fbasic-system-test%2Fpx%2Fs3%2Fpx-backup-system-test-vanilla/detail/px-backup-system-test-vanilla/544/pipeline)

**Comment by mkoppal-px** [comment]
Please merge after getting approval from @lsrinivas-pure and @Madanagopal19

**Review by lsrinivas-pure — APPROVED** [review]
LGTM

**Review by Madanagopal19 — APPROVED** [review]
lgtm

**Pull request merged**
