### PR TITLE
 Removed unwanted method call from CreateApplicationClusters

### PR DESCRIPTION
**Pull request by snigdha-px**
**What this PR does / why we need it**:
Unnecessary call to clusterStatus was made in  CreateApplicationClusters function
**Which issue(s) this PR fixes** (optional)
Closes #https://portworx.atlassian.net/browse/PA-1416

**Special notes for your reviewer**:

### CODE REVIEW

**Review by trenukarya-px — APPROVED** [review]

**Review by kshithijiyer-px — APPROVED** [review]
LGTM

**Review by mkoppal-px — APPROVED** [review]
LGTM

**Review by mkoppal-px — CHANGES_REQUESTED** [review]
Can you please run a couple of tests calling `CreateApplicationClusters `

**Comment by snigdha-px** [comment]
> Can you please run a couple of tests calling `CreateApplicationClusters `

sure

**Comment by snigdha-px** [comment]
> Can you please run a couple of tests calling `CreateApplicationClusters `

Run is going on : https://aetos.pwx.purestorage.com/resultSet/testSetID/271392
[failures are not related to my changes]

**Comment by snigdha-px** [comment]
> > Can you please run a couple of tests calling `CreateApplicationClusters `
> 
> https://aetos.pwx.purestorage.com/resultSet/testSetID/271392 [failures are not related to my changes]

New run started: https://aetos.pwx.purestorage.com/resultSet/testSetID/271749

**Review by kphalgun-px — APPROVED** [review]
LGTM

**Pull request merged**
