### PR TITLE
[PTX-2232] Added logic to validate applications restored by backup

### PR DESCRIPTION
**Pull request by vinayakshnd**

### CODE REVIEW

**Comment by thiguetta** [comment]
@vinayakshnd this might impact other scenarios, so please run a dev-test job with a non-backup scenario these cases `SetupTeardown,AppTasksDown,AppScaleUpAndDown,VolumeDriverDown,VolumeDriverAppDown,VolumeDriverDownAttachedNode,VolumeUpdate,RebootOneNode` and paste the link here, you can use these apps `mysql, postgres, elasticsearch, nginx-sharedv4, wordpress-sharedv4`

**Comment by vinayakshnd** [comment]
Recent tp-dev-test job failed with [PWX-13637](https://portworx.atlassian.net/browse/PWX-13637)
https://jenkins.portworx.co/job/Torpedo/job/tp-dev-test/652/console

**Comment by vinayakshnd** [comment]
tp-dev-test passed with `VolumeUpdate,StopScheduler` on `elasticsearch,mysql,nginx,nginx-sharedv4,postgres,wordpress-sharedv4`
https://jenkins.portworx.co/job/Torpedo/job/tp-dev-test/684/parameters/

**Comment by thiguetta** [comment]
@vinayakshnd checked the logs and RebootAllNodes is not a valid test, can you please run using `RebootOneNode` is the correct one, could you please run at least with this test?

**Comment by vinayakshnd** [comment]
@thiguetta tp-dev-test passed with `RebootOneNode` here: https://jenkins.portworx.co/job/Torpedo/job/tp-dev-test/686/

**Pull request merged**
