### PR TITLE
Storage class auth annot

### PR DESCRIPTION
**Pull request by Rohit-PX**
Why do we need this PR?

For auth-enabled PX clusters, security annotations must be added to storage classes under `parameters` instead of directly adding to PVC annotations or other storage object annotations

### CODE REVIEW

**Comment by harsh-px** [comment]
@Rohit-PX the PR says annotations need to be added on the StorageClass but the PR is adding them in the MigrationSchedule. Am I missing something?

**Comment by Rohit-PX** [comment]
> @Rohit-PX the PR says annotations need to be added on the StorageClass but the PR is adding them in the MigrationSchedule. Am I missing something?

I missed a commit during squash, let me correct it.

**Comment by Rohit-PX** [comment]
@harsh-px I created this PR by mistakenly using an old branch. Will close this and create another.

**Comment by Rohit-PX** [comment]
Was using a stale branch, create a new PR here:  https://github.com/portworx/torpedo/pull/536

**Pull request closed without merging**
