### PR TITLE
Added testrail ID and cleanup for a testcase

### PR DESCRIPTION
**Pull request by snigdha-px**
**What this PR does / why we need it**:
1)Added a test ID for testcase PXBackupEndToEndBackupAndRestoreWithUpgrade
2)Added namespace label cleanup for BackupScheduleForOldAndNewNS
3)Changed the schedule time interval from 5 min to 15 min for tc: AddMultipleNamespaceLabels
**Which issue(s) this PR fixes** (optional)
Closes #
(https://portworx.atlassian.net/browse/PA-1166)
**Special notes for your reviewer**:

### CODE REVIEW

**Review by vpinisetti-px — APPROVED** [review]
LGTM

**Review by sn-px — APPROVED** [review]

**Review by ak-px — APPROVED** [review]
LGTM

**Review by kshithijiyer-px — COMMENTED** [review]
Can you please check why the CBT checks are failing?

**Review by mkoppal-px — APPROVED** [review]
LGTM

**Review by kshithijiyer-px — APPROVED** [review]
LGTM

**Pull request merged**
