### PR TITLE
Removing restores from list which are not created

### PR DESCRIPTION
**Pull request by snigdha-px**
**What this PR does / why we need it**:

We are trying to cleanup the restore which are not even created
Trying to restore a cloud file missing backup → restore will not go through
This restore should not be added as part of cleanup
Removed this restore from the restore list

**Which issue(s) this PR fixes** (optional)
Closes #https://purestorage.atlassian.net/browse/PB-6437

**Special notes for your reviewer**:

### CODE REVIEW

**Review by ak-px — APPROVED** [review]
LGTM

**Review by vpinisetti-px — APPROVED** [review]
Got it. LGTM

**Review by sn-px — APPROVED** [review]
LGTM

**Review by sabrarhussaini — APPROVED** [review]
LGTM

**Review by kshithijiyer-px — APPROVED** [review]
LGTM

**Review by kphalgun-px — APPROVED** [review]
LGTM

**Review by mkoppal-px — APPROVED** [review]
LGTM

**Pull request merged**
