### PR TITLE
PB-6466: Remove non-existing test from `backup_test_labels.go`

### PR DESCRIPTION
**Pull request by kshithijiyer-px**
**What this PR does / why we need it**:
- [x]  Remove non-existing test from `backup_test_labels.go`

**Which issue(s) this PR fixes** (optional)
Closes #PB-6466

**Special notes for your reviewer**:

### CODE REVIEW

**Review by ak-px — APPROVED** [review]
LGTM

**Comment by kshithijiyer-px** [comment]
> aetosl1nfs tag need to be added

Yes! Nice catch added.

**Comment by mkoppal-px** [comment]
@kshithijiyer-px Please remove the entry for `ManualAndScheduleBackupUsingNamespaceLabel` since it is not there anymore

**Comment by kshithijiyer-px** [comment]
> @kshithijiyer-px Please remove the entry for `ManualAndScheduleBackupUsingNamespaceLabel` since it is not there anymore

Done

**Review by mkoppal-px — APPROVED** [review]
LGTM

**Pull request merged**
