### PR TITLE
Made changes for revert done with PB-4621

### PR DESCRIPTION
**Pull request by ak-px**
**What this PR does / why we need it**:
Made changes for revert done with PB-4621

**Which issue(s) this PR fixes** (optional)
Closes #PA-1775

**Special notes for your reviewer**:
Vanilla s3:
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/basic-system-test/job/px/job/s3/job/px-backup-system-test-vanilla/509/
https://aetos.pwx.purestorage.com/resultSet/testSetID/402327

Test ran for particular failed test.
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/3162/consoleFull
https://aetos.pwx.purestorage.com/resultSet/testSetID/403776

RKE run in progress
https://aetos.pwx.purestorage.com/resultSet/testSetID/403771

### CODE REVIEW

**Review by mkoppal-px — CHANGES_REQUESTED** [review]
@ak-px Can you please check `ClusterBackupShareToggle` is failing with `rpc error: code = Internal desc = failed to retrieve cluster [source-cluster]: more than one object found with same name, please use the object UID along with name`

Looks like it is related to the changes made here.

**Comment by ak-px** [comment]
> @ak-px Can you please check `ClusterBackupShareToggle` is failing with `rpc error: code = Internal desc = failed to retrieve cluster [source-cluster]: more than one object found with same name, please use the object UID along with name`
> 
> Looks like it is related to the changes made here.

This was due uid was missing in DeleteSchedule clusterinspect. The latest commit contain those changes as well.
Test ran for particular failed test.
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/3162/consoleFull
https://aetos.pwx.purestorage.com/resultSet/testSetID/403776

**Review by mkoppal-px — APPROVED** [review]
LGTM

**Review by kphalgun-px — APPROVED** [review]
LGTM

**Pull request merged**
