### PR TITLE
Fixed DeleteSharedBackupOfUserFromAdmin failure

### PR DESCRIPTION
**Pull request by ak-px**
**What this PR does / why we need it**:

Fixed DeleteSharedBackupOfUserFromAdmin,clusterUid was send as null in delete backup call as wrong user info is passed.

**Which issue(s) this PR fixes** (optional)
Closes #PB-4817

**Special notes for your reviewer**:
log:
IBM:
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/basic-system-test/job/nonpx/job/ibm/job/s3/job/ibm-s3-nativecsi/34/console
Vanilla:
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/3211/console
https://aetos.pwx.purestorage.com/resultSet/testSetID/415206

### CODE REVIEW

**Comment by kshithijiyer-px** [comment]
@ak-px can you please check why CBT is it failing?

**Comment by ak-px** [comment]
> @ak-px can you please check why CBT is it failing?

Failed due to https://portworx.atlassian.net/browse/PTX-20998

**Review by mkoppal-px — APPROVED** [review]
LGTM

**Review by kshithijiyer-px — APPROVED** [review]
LGTM

**Pull request merged**
