### PR TITLE
Added code to get backup status before proceeding for restore for test case SwapShareBackup

### PR DESCRIPTION
**Pull request by snigdha-px**
**What this PR does / why we need it**:
Testcase SwapShareBackup is failing intermittently . When trying to restore the shared backup, it fails with error that backup is not in success state
We do not have sufficient logs to see what state the backup is in and the reason for that state
hence added GetBackupStatusWithReason before restoring the backup
**Which issue(s) this PR fixes** (optional)
Closes #https://portworx.atlassian.net/browse/PB-5663

**Special notes for your reviewer**:

log : https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/4641/consoleFull
https://aetos.pwx.purestorage.com/resultSet/testSetID/558632/testCaseID/3353536

### CODE REVIEW

**Review by atrivedi-px — APPROVED** [review]
LGTM

**Review by mkoppal-px — APPROVED** [review]
LGTM

**Review by kshithijiyer-px — APPROVED** [review]
LGTM

**Comment by kphalgun-px** [comment]
How about we log the backup status and reason in CreateRestore?

**Comment by snigdha-px** [comment]
> How about we log the backup status and reason in CreateRestore?

Backup status is validated in all the other testcases as we use CreateBackupAndValidate
Only for this testcase backup status is not validated after sharing , hence added
Adding in "CreateRestore" will be duplicate verification

**Comment by kphalgun-px** [comment]
> Only for this testcase backup status is not validated after sharing , hence added

I wanted to log the backup status and reason to help with future debugging. If this is the only test case that does not validate the shared backup, then I guess it is fine.

**Pull request merged**
