### PR TITLE
PB-5707: Assign labels to the backup tests in torpedo

### PR DESCRIPTION
**Pull request by kshithijiyer-px**
**What this PR does / why we need it**:
- [x] Assign labels to the backup tests in torpedo
- [x] Update the Describe of all the cases with corresponding map string

Test results by doing a dry run:
```
➜  backup git:(topic/kshithijiyer/PB-5707) ✗ ginkgo --dry-run -v --label-filter='vanilla-pipeline-s3' -- -spec-dir /Users/kiyer/code/torpedo/drivers/scheduler/k8s/specs -log-location `pwd` --app-list postgres-backup --backup-driver pxb --product px-backup --test-desc "Px-Backup System Tests" --user kiyer | awk '{
    while(match($0, /\{[^}]*\}/)){
        print substr($0, RSTART + 1, RLENGTH - 2);
        $0 = substr($0, RSTART + RLENGTH);
    }
}'

MultipleInPlaceRestoreSameTime
BackupSyncBasicTest
ManualAndScheduleBackupUsingNSLabelWithMaxCharLimit
DeleteUserBackupsAndRestoresOfDeletedAndInActiveClusterFromAdmin
VerifyRBACForInfraAdmin
ScheduleBackupWithAdditionAndRemovalOfNS
VerifyRBACForAppUser
UpdatesBackupOfUserFromAdmin
NamespaceLabelledBackupOfEmptyNamespace
CreateMultipleUsersAndGroups
VerifyRBACForPxAdmin
IssueDeleteOfIncrementalBackupsAndRestore
ScaleDownPxBackupPodWhileBackupAndRestoreIsInProgress
DeleteBackupAndCheckIfBucketIsEmpty
RestoreEncryptedAndNonEncryptedBackups
DeleteSharedBackupOfUserFromAdmin
VerifyRBACForAppAdmin
AllNSBackupWithIncludeNewNSOption
DuplicateSharedBackup
ShareBackupWithDifferentRoleUsers
KillStorkWithBackupsAndRestoresInProgress
BasicSelectiveRestore
BackupRestartPX
DeleteSameNameObjectsByMultipleUsersFromAdmin
ReplicaChangeWhileRestore
DeleteNSDeleteClusterRestore
CancelClusterBackupShare
IssueMultipleRestoresWithNamespaceAndStorageClassMapping
BackupLocationWithEncryptionKey
ShareBackupAndEdit
ScheduleBackupDeleteAndRecreateNS
DeleteUsersRole
LicensingCountWithNodeLabelledBeforeClusterAddition
CancelAllRunningRestoreJobs
ManualAndScheduledBackupUsingNamespaceAndResourceLabel
ViewOnlyFullBackupRestoreIncrementalBackup
MultipleCustomRestoreSameTimeDiffStorageClassMapping
SharedBackupDelete
LicensingCountBeforeAndAfterBackupPodRestart
BasicBackupCreation
ResizeOnRestoredVolume
SetUnsetNSLabelDuringScheduleBackup
DeleteS3ScheduleAndCreateNfsSchedule
DeleteBackupSharedByMultipleUsersFromAdmin
CustomResourceRestore
SwapShareBackup
ShareAndRemoveBackupLocation
DeleteBackupOfUserSharedRBAC
ResizeVolumeOnScheduleBackup
DeleteSharedBackup
DeleteIncrementalBackupsAndRecreateNew
CustomResourceBackupAndRestore
DeleteAllBackupObjects
ScheduleBackupCreationAllNS
RestartBackupPodDuringBackupSharing
CancelAllRunningBackupJobs
NodeCountForLicensing
KubeAndPxNamespacesSkipOnAllNSBackup
ScaleMongoDBWhileBackupAndRestore
DeleteObjectsByMultipleUsersFromNewAdmin
CloudSnapsSafeWhenBackupLocationDeleteTest
DeleteBackupOfUserNonSharedRBAC
DeleteBucketVerifyCloudBackupMissing
ShareBackupsAndClusterWithUser
ClusterBackupShareToggle
BackupMultipleNsWithSameLabel
IssueMultipleDeletesForSharedBackup
NamespaceLabelledBackupSharedWithDifferentAccessMode
AlternateBackupBetweenNfsAndS3
BackupScheduleForOldAndNewNS
DifferentAccessSameUser
ShareBackupWithUsersAndGroups
DeleteFailedInProgressBackupAndRestoreOfUserFromAdmin
RebootNodesWhenBackupsAreInProgress
BackupNamespaceInNfsRestoredFromS3
AddMultipleNamespaceLabels
➜  backup git:(topic/kshithijiyer/PB-5707) ✗ ginkgo --dry-run -v --label-filter='vanilla-pipeline-with-s3-locked-bucket' -- -spec-dir /Users/kiyer/code/torpedo/drivers/scheduler/k8s/specs -log-location `pwd` --app-list postgres-backup --backup-driver pxb --product px-backup --test-desc "Px-Backup System Tests" --user kiyer | awk '{
    while(match($0, /\{[^}]*\}/)){
        print substr($0, RSTART + 1, RLENGTH - 2);
        $0 = substr($0, RSTART + RLENGTH);
    }
}'

LockedBucketResizeOnRestoredVolume
BackupToLockedBucketWithSharedObjects
LockedBucketResizeVolumeOnScheduleBackup
BackupAlternatingBetweenLockedAndUnlockedBuckets
➜  backup git:(topic/kshithijiyer/PB-5707) ✗ ginkgo --dry-run -v --label-filter='vanilla-pipeline-with-different-k8s-versions-nfs' -- -spec-dir /Users/kiyer/code/torpedo/drivers/scheduler/k8s/specs -log-location `pwd` --app-list postgres-backup --backup-driver pxb --product px-backup --test-desc "Px-Backup System Tests" --user kiyer | awk '{
    while(match($0, /\{[^}]*\}/)){
        print substr($0, RSTART + 1, RLENGTH - 2);
        $0 = substr($0, RSTART + RLENGTH);
    }
}'

BackupCRsThenMultipleRestoresOnHigherK8sVersion
BackupRestoreOnDifferentK8sVersions

```

**Which issue(s) this PR fixes** (optional)
Closes #PB-5707

**Special notes for your reviewer**:

### CODE REVIEW

**Review by kphalgun-px — APPROVED** [review]
LGTM

**Review by sn-px — APPROVED** [review]
LGTM

**Comment by mkoppal-px** [comment]
@kshithijiyer-px  Firstly, thanks for taking this up. This was much needed.
Can you please trigger a pipeline with labels and make sure everything is fine?

**Comment by kshithijiyer-px** [comment]
> @kshithijiyer-px Firstly, thanks for taking this up. This was much needed. Can you please trigger a pipeline with labels and make sure everything is fine?

Done https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/4957/console

**Review by mkoppal-px — APPROVED** [review]
LGTM

**Pull request merged**
