### PR TITLE
[PTX-22666] Fix GetWaitTime

### PR DESCRIPTION
**Pull request by kphalgun-px**
**What this PR does / why we need it**:
This PR addresses an issue with GetWaitTime used by longevity test cases. It has been updated to consult the triggerInterval when a baseInterval is not specified in the longevity-triggers config map.

**Which issue(s) this PR fixes** (optional)
Closes #PTX-22666

**Special notes for your reviewer**:
I will update once the test run is complete.

### CODE REVIEW

**Review by atrivedi-px — APPROVED** [review]
LGTM.
This may need to be rebased with current master as the changes should be in longevity_helper.

**Comment by kphalgun-px** [comment]
> LGTM. This may need to be rebased with current master as the changes should be in longevity_helper.

Done.

**Review by lsrinivas-pure — APPROVED** [review]
LGTM

**Review by mkoppal-px — APPROVED** [review]
LGTM

**Pull request merged**
