### PR TITLE
Analyse stork test failures in full test pipelines - Added log statements to debug failures

### PR DESCRIPTION
**Pull request by atrivedi-px**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** (optional)
Closes #PB-5898

**Special notes for your reviewer**:
https://aetos.pwx.purestorage.com/resultSet/testSetID/580177
Latest Run: https://aetos.pwx.purestorage.com/resultSet/testSetID/581114

### CODE REVIEW

**Review by mkoppal-px — CHANGES_REQUESTED** [review]
The test results are not conclusive. In the first link it has failed and in the second link it has not yet reached the test case.

**Comment by atrivedi-px** [comment]
> The test results are not conclusive. In the first link it has failed and in the second link it has not yet reached the test case.

BackupAndRestoreWithNonExistingAdminNamespaceAndUpdatedResumeSuspendBackupPolicies passed in both the runs, also the other tests failures are in deletion which is not related to this PR.

**Review by mkoppal-px — APPROVED** [review]
LGTM

**Review by kshithijiyer-px — APPROVED** [review]
LGTM

**Pull request merged**
