### PR TITLE
PA-1395: Add sh file for clouds

### PR DESCRIPTION
**Pull request by kshithijiyer-px**
**What this PR does / why we need it**:
- [x] Add sh file for clouds

Jenkins Workspace with the xml: https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/basic-system-test/job/nonpx/job/Px-Backup-IKS-non-px-s3/33/execution/node/5/ws/testresults/ 

Pass jenkins run: https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/basic-system-test/job/nonpx/job/Px-Backup-IKS-non-px-s3/42/console

**Which issue(s) this PR fixes** (optional)
Closes #PA-1395

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by kshithijiyer-px** [comment]
Screenshot 2023-07-28 at 5 24 13 PM

**Comment by mkoppal-px** [comment]
@kshithijiyer-px Why is `BasicBackupCreation` failing?

**Review by mkoppal-px — APPROVED** [review]
I think you need to add these params in the sh file

```
    - name: VOLUME_SNAPSHOT_CLASS
      value: "${VOLUME_SNAPSHOT_CLASS}"
```

**Comment by kshithijiyer-px** [comment]
> I think you need to add these params in the sh file
> 
> ```
>     - name: VOLUME_SNAPSHOT_CLASS
>       value: "${VOLUME_SNAPSHOT_CLASS}"
> ```

Thanks for pointing out have added it.

**Comment by mkoppal-px** [comment]
Look good. Can you run the same test again and make sure it is green?

**Comment by kshithijiyer-px** [comment]
> Looks good. Can you run the same test again and make sure it is green?

Yes have triggered the run will add the details once it's done. 
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/basic-system-test/job/nonpx/job/Px-Backup-IKS-non-px-s3/34/

**Comment by kshithijiyer-px** [comment]
> > Looks good. Can you run the same test again and make sure it is green?
> 
> Yes have triggered the run will add the details once it's done. https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/basic-system-test/job/nonpx/job/Px-Backup-IKS-non-px-s3/34/

This failed due to infra issues. Now have fixed it and reran will update the thread once it's done.

**Comment by kshithijiyer-px** [comment]
Successful job: https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/basic-system-test/job/nonpx/job/Px-Backup-IKS-non-px-s3/42/console

Screenshot 2023-07-31 at 12 02 38 PM

**Review by ak-px — APPROVED** [review]
LGTM

**Review by mkoppal-px — APPROVED** [review]
Solid fix. Thanks @kshithijiyer-px 👍

**Pull request merged**
