### PR TITLE
PTX-1404 add subpath to wordpress

### PR DESCRIPTION
**Pull request by thiguetta**

### CODE REVIEW

**Comment by harsh-px** [comment]
@thiguetta , can we also queue to run this app in your dev test job?

**Comment by thiguetta** [comment]
tests running here https://jenkins.portworx.co/job/Torpedo/job/tp-dev-test/224/console we can merge once done

**Comment by thiguetta** [comment]
test passed

**Comment by harsh-px** [comment]
Can you try adding wordpress to one of the stable official jobs

**Pull request merged**
